// Disposable Postgres fixture. Production auth helper definitions must be recovered separately.
import { PGlite } from '@electric-sql/pglite';
import fs from 'node:fs';
import assert from 'node:assert/strict';
const db=new PGlite(),R=new URL('../',import.meta.url),sql=n=>fs.readFileSync(new URL(n,R),'utf8');
let checks=0;const ok=(v,label)=>{assert.ok(v,label);checks++;console.log('ok',label)};
const q=async(s,p)=>(await db.query(s,p)).rows;
const rejects=async(s)=>{try{await db.exec(s);return false}catch{return true}};
const id=n=>`00000000-0000-0000-0000-${String(n).padStart(12,'0')}`;
const A=id(1),B=id(2),C=id(3),D=id(4),CY=id(10),OLD=id(11),CA=id(20),CB=id(21),CC=id(22);
const as=async who=>db.exec(`reset role;select set_config('request.jwt.claim.sub','${who||''}',false);set role ${who?'authenticated':'anon'};`);
await db.exec(`create role authenticated;create role anon;create schema auth;create table auth.users(id uuid primary key,email text,email_confirmed_at timestamptz);create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;grant usage on schema public,auth to authenticated,anon;`);
await db.exec(sql('01-schema.sql').replace(/create extension[^;]*;/,''));
await db.exec(sql('02-views.sql'));await db.exec(sql('03-policies.sql'));
await db.exec(`alter table members add column role text;create table roles(name text primary key,is_admin boolean,in_recruitment boolean,in_training boolean,sort_order int);
insert into roles values('Recruitment Committee',false,true,false,1),('Training Committee',false,false,true,2),('Admin',true,true,true,0);
create function in_recruitment() returns boolean language sql stable security definer set search_path=public as $$select exists(select 1 from members m join roles r on r.name=m.role where m.id=auth.uid() and m.active and r.in_recruitment)$$;
create function in_training() returns boolean language sql stable security definer set search_path=public as $$select exists(select 1 from members m join roles r on r.name=m.role where m.id=auth.uid() and m.active and r.in_training)$$;
insert into auth.users(id,email) values('${A}','a@test'),('${B}','b@test'),('${C}','c@test'),('${D}','d@test');
insert into members(id,full_name,email,role,is_codirector) values('${A}','Same Name','a@test','Recruitment Committee',false),('${B}','Same Name','b@test','Recruitment Committee',false),('${C}','Admin','c@test','Admin',true),('${D}','Training','d@test','Training Committee',false);
insert into interview_cycles(id,label,is_current) values('${CY}','Current',true),('${OLD}','History',false);
insert into candidates(id,cycle_id,name) values('${CA}','${CY}','Avery'),('${CB}','${CY}','Blair'),('${CC}','${OLD}','Historical');
grant select,insert,update,delete on all tables in schema public to authenticated,anon;`);
await db.exec(sql('08-access.sql'));
const before=JSON.stringify(await q('select * from candidates order by id'));
await db.exec(sql('22-interview-safety.sql'));await db.exec(sql('22-interview-safety.sql'));
ok(JSON.stringify(await q('select * from candidates order by id'))===before,'migration reruns without altering candidates');
await as(A);
await db.exec(`insert into interview_scores(candidate_id,interviewer_id,speaking,personable,impression,note) values('${CA}','${A}',5,1,3,'Alice note')`);
ok(await rejects(`insert into interview_scores(candidate_id,interviewer_id,speaking) values('${CA}','${B}',1)`),'cannot insert another evaluator score');
ok(await rejects(`select interview_save_settings('${CY}',array['A'],array['${A}'::uuid])`),'nonadmin cannot configure panel');
ok(await rejects(`select interview_replace_unscored('${CY}','[{"name":"X"}]')`),'nonadmin cannot replace roster');
await as(B);await db.exec(`insert into interview_scores(candidate_id,interviewer_id,speaking,note) values('${CA}','${B}',1,'Bob note')`);
ok((await q(`update interview_scores set note='overwrite' where interviewer_id='${A}' returning *`)).length===0,'cannot update another evaluator');
ok((await q(`delete from interview_scores where interviewer_id='${A}' returning *`)).length===0,'cannot delete another evaluator');
ok((await q(`select * from interview_scores where candidate_id='${CA}'`)).length===2,'independent evaluator rows coexist');
const result=(await q(`select * from candidate_results where id='${CA}'`))[0];
ok(Math.abs(Number(result.final)-7/3)<1e-10&&Number(result.raters)===2,'SQL averages preserve existing partial-score semantics');
ok(await rejects(`update interview_scores set speaking=6 where interviewer_id='${B}'`),'database rejects out-of-range scores');
await as(D);ok((await q('select * from interview_scores')).length===0,'training cannot read interview comments');ok((await q('select * from candidate_results')).length===0,'view honors RLS');
ok(await rejects(`insert into interview_scores(candidate_id,interviewer_id,speaking) values('${CA}','${D}',3)`),'training cannot score');
await as(null);ok((await q('select * from interview_scores')).length===0,'anonymous cannot read scores');ok(await rejects(`select interview_save_settings('${CY}',array['A'],array[]::uuid[])`),'anonymous cannot call settings');
await as(C);ok((await q(`update interview_scores set note='overwrite' where interviewer_id='${A}' returning *`)).length===0,'admin cannot overwrite another evaluator');
ok(await rejects(`delete from candidates where id='${CA}'`),'scored candidate deletion blocked');
ok(await rejects(`select interview_replace_unscored('${CY}','[{"name":"Replacement"}]')`),'replace cannot destroy scores');
ok((await q(`select * from candidates where cycle_id='${CY}'`)).length===2,'failed replacement is atomic');
await db.exec(`select interview_save_settings('${CY}',array['A','B'],array['${A}'::uuid,'${B}'::uuid])`);
ok((await q('select * from interview_panel')).length===2,'admin configures expected panel');
await db.exec(`select interview_save_settings('${CY}',array['A'],array['${A}'::uuid])`);
ok((await q(`select * from interview_scores where interviewer_id='${B}'`)).length===1,'panel removal preserves historical identity and comments');
ok(await rejects(`select interview_save_settings('${OLD}',array['A'],array[]::uuid[])`),'historical settings protected');
ok((await q(`delete from candidates where id='${CB}' returning *`)).length===1,'unscored applicant can be removed');
await db.exec('reset role');
await db.exec(`update interview_cycles set is_current=false;insert into interview_cycles(id,label,is_current) values('${id(12)}','New',true);insert into candidates(cycle_id,name) values('${id(12)}','Unscored')`);
await as(C);ok(await rejects(`select interview_replace_unscored('${id(12)}','[{"name":""}]')`),'invalid replacement fails validation');
ok(await rejects(`select interview_replace_unscored('${id(12)}',null)`),'null replacement cannot clear roster');
ok((await q(`select name from candidates where cycle_id='${id(12)}'`))[0].name==='Unscored','failed import restores old roster');
ok((await q(`select interview_replace_unscored('${id(12)}','[{"name":"New applicant"}]') n`))[0].n===1,'unscored replacement succeeds atomically');
ok((await q(`select * from candidates where id='${CC}'`)).length===1,'historical candidate untouched');
await db.exec('reset role');
await db.exec(sql('23-interview-samples.sql'));await db.exec(sql('23-interview-samples.sql'));
await as(C);
const sampleResult=(await q(`select interview_load_samples('${id(12)}') result`))[0].result;
ok(sampleResult.added===3&&sampleResult.total===3,'admin imports three checked-in samples');
const sampleIds=(await q('select candidate_id from interview_samples')).map(r=>r.candidate_id);
ok((await q(`select * from candidates where id=any($1::uuid[]) and checked_in_at is not null`,[sampleIds])).length===3,'sample applicants are ready to evaluate');
ok((await q(`select * from interview_scores where candidate_id=any($1::uuid[]) and interviewer_id=$2`,[sampleIds,C])).length===2,'example evaluations belong only to the importing admin');
const partial=(await q(`select * from interview_scores where candidate_id=any($1::uuid[]) and personable is null`,[sampleIds]))[0];
ok(partial?.speaking===4&&partial?.impression===null,'sample includes an incomplete evaluation');
await q(`update interview_scores set note='Keep my sample edits' where candidate_id=$1`,[partial.candidate_id]);
ok((await q(`select interview_load_samples('${id(12)}') result`))[0].result.added===0,'repeated imports are idempotent');
ok((await q(`select note from interview_scores where candidate_id=$1`,[partial.candidate_id]))[0].note==='Keep my sample edits','repeat import preserves sample edits');
await as(A);
ok(await rejects(`select interview_load_samples('${id(12)}')`),'ordinary interviewer cannot import samples');
ok(await rejects(`select interview_remove_samples('${id(12)}')`),'ordinary interviewer cannot remove samples');
ok(await rejects(`insert into interview_samples(candidate_id,cycle_id,sample_key) values('${CA}','${id(12)}','avery')`),'caller cannot mark real data as disposable samples');
await as(D);ok((await q('select * from interview_samples')).length===0,'sample registry respects Recruitment visibility');
await as(C);
const real=(await q(`select id from candidates where cycle_id='${id(12)}' and id not in(select candidate_id from interview_samples)`))[0].id;
await q(`update candidates set name='Sample — Avery Example' where id=$1`,[real]);
await q(`insert into interview_scores(candidate_id,interviewer_id,note) values($1,$2,'Real evaluation remains')`,[real,C]);
ok((await q(`select interview_remove_samples('${id(12)}') n`))[0].n===3,'cleanup removes only registry-proven samples');
ok((await q(`select note from interview_scores where candidate_id=$1`,[real]))[0].note==='Real evaluation remains','cleanup preserves real evaluations even with identical sample names');
ok((await q(`select * from candidates where id='${CC}'`)).length===1,'sample workflow leaves history unchanged');
ok((await q(`select interview_remove_samples('${id(12)}') n`))[0].n===0,'repeated sample cleanup is safe');
console.log(`${checks} interview SQL checks passed.`);await db.close();
