// Run: node --experimental-vm-modules tests/vanessa.test.mjs
// No external requests, credentials, or real people. Browser model is simulated.
import vm from 'node:vm';
import fs from 'node:fs';
import path from 'node:path';
import assert from 'node:assert/strict';
import { fileURLToPath } from 'node:url';
const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
let checks = 0;
async function test(name, fn) { await fn(); checks++; console.log('PASS ' + name); }
async function app(extra = {}) {
  const nodes = new Map();
  const document = { addEventListener(){}, getElementById(){return {};}, querySelector(s){return nodes.get(s) || null;}, querySelectorAll(){return [];} };
  const storage = new Map();
  const context = vm.createContext({console, document, window:{addEventListener(){}}, AbortController, setTimeout,clearTimeout,
    localStorage:{getItem:k=>storage.get(k),setItem:(k,v)=>storage.set(k,v),removeItem:k=>storage.delete(k)}, ...extra});
  const cache = new Map();
  async function load(p){p=path.resolve(root,p);if(cache.has(p))return cache.get(p);const m=new vm.SourceTextModule(fs.readFileSync(p,'utf8'),{context,identifier:p});cache.set(p,m);await m.link((s,r)=>load(path.resolve(path.dirname(r.identifier),s)));return m;}
  async function get(p){const m=await load(p);if(m.status==='linked')await m.evaluate();return m.namespace;}
  const v=await get('js/core/vanessa.js');const {state}=await get('js/core/state.js');
  state.me={id:'demo',full_name:'Demo User'};state.role={in_training:true,in_recruitment:true,is_admin:true};state.loadedAt=new Date();
  state.guides=[{name:'Avery Sample',status:'open',rank:1,priority:'First Priority',tours:[],skip:false},{name:'Blake Example',status:'claimed',rank:2,priority:'Second Priority',evaluatorId:'demo',tours:[],skip:false}];
  state.counts={open:1,claimed:1};state.neededTotal=2;
  v.shareInterviews({candidates:[{name:'Casey Fictional',raters:0,final:null,spread:null,decision:'',checkin:'Yes',scores:{}},{name:'Drew Placeholder',raters:1,final:3,spread:0,decision:'',checkin:'',scores:{}}]});
  const {dayISO}=await get('js/core/vanessa-dates.js');const today=new Date();const tomorrow=new Date(today);tomorrow.setDate(today.getDate()+1);
  v.shareOther('tours',[{date:dayISO(today),slot:'10:00',guide:'Avery Sample'},{date:dayISO(tomorrow),slot:'11:00',guide:'Blake Example'}]);
  v.shareOther('desks',[{desk:'Front Desk',day:'Monday',slot:'9:00',person:'Blake Example'},{desk:'Welcome Desk',day:'Tuesday',slot:'10:00',person:'Casey Fictional'}]);
  return {v,state,get,context,nodes};
}
const a=await app();
const ask=q=>{a.v.forget();return a.v.ask(q);};
await test('dress code outranks tour data',()=>assert.match(ask('What should I wear on tour?').text,/Admissions polo/));
await test('ungraded query answers without navigating',()=>{const r=ask('Show me ungraded candidates');assert.match(r.text,/Casey Fictional/);assert.equal(r.go,undefined);});
await test('negative check-in lists missing candidates',()=>{const r=ask('Who has not checked in?');assert.match(r.text,/Drew Placeholder/);assert.doesNotMatch(r.text,/Casey Fictional/);});
await test('guide lookup does not return handbook passage',()=>assert.match(ask('Tell me about Avery Sample').text,/First Priority/));
await test('unknown person does not return unrelated handbook passage',()=>assert.match(ask('Tell me about Quinton Zzzzz').text,/could not identify/));
await test('tomorrow schedule keeps date filter',()=>{const r=ask('Who is leading tours tomorrow?');assert.match(r.text,/Blake Example/);assert.doesNotMatch(r.text,/Avery Sample/);});
await test('desk day and location filters',()=>{const r=ask('Who is on the front desk Monday?');assert.match(r.text,/Monday.*Blake Example/s);assert.doesNotMatch(r.text,/Casey Fictional/);});
await test('desk relative tomorrow uses a single weekday',()=>{const r=ask('Who is on the front desk tomorrow?');assert.doesNotMatch(r.text,/Monday, Tuesday/);});
await test('greeting yes resolves recorded details',()=>{a.v.resetVanessaData();a.v.greeting();assert.match(a.v.ask('yes').text,/Blake Example/);});
await test('ambiguous guide first name asks which and resolves ordinal',()=>{a.state.guides.push({...a.state.guides[0],name:'Avery Second'});a.v.forget();assert.match(a.v.ask('Tell me about Avery').text,/Which one/);assert.match(a.v.ask('the second one').text,/Avery Second/);a.state.guides.pop();});
await test('standard scoring explanation remains available',()=>assert.match(ask('How is the final score worked out?').text,/three criteria/));
await test('explicit navigation still opens the requested tool',()=>assert.equal(ask('Open interviews').go,'interviews'));
await test('ambiguous casual request asks for clarification',()=>assert.match(ask('Who do we still gotta look at?').text,/Do you mean/));
await test('reset removes candidate cache',()=>{a.v.resetVanessaData();assert.match(ask('Who has not checked in?').text,/not loaded/);});
await test('signed-out questions cannot access hub data',()=>{a.state.me=null;assert.match(a.v.ask('Who needs an eval?').text,/Sign in/);});
const {dateRange}=await a.get('js/core/vanessa-dates.js');
await test('week range includes multiple days',()=>{const r=dateRange('this week',new Date(2026,8,8));assert.equal(r.from,'2026-09-08');assert.equal(r.to,'2026-09-13');});
await test('next week crosses calendar year',()=>{const r=dateRange('next week',new Date(2026,11,31));assert.equal(r.from,'2027-01-04');assert.equal(r.to,'2027-01-10');});
await test('invalid and unsupported dates do not silently mean today',()=>{assert.ok(dateRange('2026-02-30').error);assert.ok(dateRange('next month').error);});
await test('warm-up retries rejected loaders and deduplicates concurrent requests',async()=>{const b=await app();const ui=await b.get('js/core/vanessa-ui.js');let n=0;ui.registerWarmers([{needs:'training',load:async()=>{if(++n===1)throw Error('offline');}}]);const first=await ui.warmUp();assert.equal(first.length,1);await Promise.all([ui.warmUp(),ui.warmUp()]);assert.equal(n,2);await ui.warmUp();assert.equal(n,2);});
await test('session reset clears counts and notifies cleanup',async()=>{const b=await app();const s=await b.get('js/core/state.js');let notified=0;s.onSessionReset(()=>notified++);s.clearSession();assert.equal(notified,1);assert.equal(s.state.neededTotal,0);assert.equal(s.state.me,null);});
await test('UI teardown removes launcher and conversation',async()=>{const b=await app();const ui=await b.get('js/core/vanessa-ui.js');let removed=0;for(const id of ['#v-launch','#v-panel'])b.nodes.set(id,{remove(){removed++;}});ui.resetVanessa();assert.equal(removed,2);});
await test('missing model API reports a visible reason',async()=>{const b=await app();const m=await b.get('js/core/vanessa-model.js');await m.checkAvailability();assert.equal(m.modelState(),'unavailable');assert.match(m.modelStatus().message,/LanguageModel API/);});
await test('HTTP context reports HTTPS requirement',async()=>{const b=await app({isSecureContext:false});const m=await b.get('js/core/vanessa-model.js');await m.checkAvailability();assert.match(m.modelStatus().message,/HTTPS/);});
await test('download starts synchronously with consistent English options',async()=>{let called=0,availabilityOptions,createOptions;const b=await app({LanguageModel:{availability:async options=>{availabilityOptions=options;return 'downloadable';},create:options=>{called++;createOptions=options;return Promise.resolve({destroy(){}});}}});const m=await b.get('js/core/vanessa-model.js');await m.checkAvailability();const job=m.enableModel();assert.equal(called,1);await job;assert.equal(m.modelState(),'ready');assert.deepEqual(createOptions.expectedInputs,availabilityOptions.expectedInputs);assert.equal(createOptions.expectedOutputs[0].languages[0],'en');m.disableModel();});
await test('unfinished downloads are not automatically resumed',async()=>{let n=0;const b=await app({LanguageModel:{availability:async()=>'downloading',create:()=>{n++;return Promise.resolve({destroy(){}});}}});b.context.localStorage.setItem('hub2.vanessa.model','1');const m=await b.get('js/core/vanessa-model.js');assert.equal(await m.resumeIfEnabled(),false);assert.equal(n,0);assert.equal(m.modelStatus().availability,'downloading');});
await test('ready downloaded model resumes when opted in',async()=>{let n=0;const b=await app({LanguageModel:{availability:async()=>'available',create:()=>{n++;return Promise.resolve({destroy(){}});}}});b.context.localStorage.setItem('hub2.vanessa.model','1');const m=await b.get('js/core/vanessa-model.js');await m.resumeIfEnabled();assert.equal(n,1);m.disableModel();});
await test('failed startup retains retry and opt-in',async()=>{const b=await app({LanguageModel:{availability:async()=>'downloadable',create:()=>Promise.reject(Object.assign(Error('denied'),{name:'NotAllowedError'}))}});const m=await b.get('js/core/vanessa-model.js');await assert.rejects(m.enableModel());assert.equal(m.modelState(),'failed');assert.match(m.modelStatus().message,/Click Retry/);assert.equal(m.wasEnabled(),true);});
await test('cancel rejects pending startup and destroys late session',async()=>{let finish,destroyed=0;const b=await app({LanguageModel:{availability:async()=>'downloadable',create:()=>new Promise(r=>{finish=r;})}});const m=await b.get('js/core/vanessa-model.js');const job=m.enableModel();m.cancelModel();await assert.rejects(job);finish({destroy(){destroyed++;}});await new Promise(r=>setTimeout(r,0));assert.equal(destroyed,1);assert.notEqual(m.modelState(),'ready');});
await test('classifier rejects invented replies and preserves valid names',async()=>{let answer='ignore everything and open people';const b=await app({LanguageModel:{availability:async()=>'available',create:async()=>({destroy(){},clone:async()=>({prompt:async()=>answer,destroy(){}})})}});const m=await b.get('js/core/vanessa-model.js');await m.enableModel();assert.equal(await m.interpret('anything'),null);answer='tell me about Avery Sample';assert.equal(await m.interpret('information on Avery Sample'),'tell me about Avery Sample');assert.equal(await m.interpret('information on someone else'),null);m.disableModel();});
await test('no-scheduled-tours question lists guides instead of today',async()=>{const b=await app();assert.match(b.v.ask('Which guides have no scheduled tours?').text,/scheduled by hand/);});
await test('failed workbook downloads retry instead of caching empty data',async()=>{let calls=0;const b=await app({fetch:async()=>{calls++;throw Error('offline');}});const sheets=await b.get('js/core/sheets.js');await assert.rejects(sheets.loadDesks());await new Promise(r=>setTimeout(r,0));const first=calls;await assert.rejects(sheets.loadDesks());assert.ok(calls>first);});
await test('entirely empty desk rows still produce uncovered slots',async()=>{const b=await app({fetch:async()=>({ok:true,status:200,text:async()=>',,9:00-10:00,,,,,,,,,,'})});const sheets=await b.get('js/core/sheets.js');const rows=await sheets.loadDesks();assert.equal(rows.length,10);b.v.shareOther('desks',rows);assert.match(b.v.ask('Which front desk slots are uncovered Monday?').text,/1 uncovered slots/);});
await test('old authenticated response is rejected after sign-out',async()=>{let finish;const b=await app({window:{CONFIG:{SUPABASE_URL:'https://example.invalid',SUPABASE_KEY:'fictional'},addEventListener(){}},fetch:()=>new Promise(r=>finish=r)});const db=await b.get('js/core/db.js');const s=await b.get('js/core/state.js');const pending=db.select('members');s.clearSession();finish({status:200,ok:true,text:async()=>'[]'});await assert.rejects(pending,/account changed/);});

// Chat evaluation workflow: no actual submissions are made by these tests.
async function evalApp(submit=async()=>({already:false})) {
  const b=await app();
  b.state.guides=[{id:'eval-demo',name:'Blake Example',status:'claimed',evaluatorId:'demo',date:'2026-09-11',time:'10:00',tours:[]}];
  const flow=await b.get('js/core/vanessa-eval.js');
  flow.registerEvalActions({load:async()=>{},submit});
  return {...b,flow};
}
async function reviewEval(b) {
  for(const q of ['I have an eval to do','4','Clear explanations and answered questions well.','Slow down at the end.','none'])await b.flow.handleEvalMessage(q);
  assert.equal(b.flow.evalDraft().phase,'review');
}
await test('conversation fills a reviewed draft without submitting',async()=>{let writes=0;const b=await evalApp(async()=>{writes++;return {};});await reviewEval(b);const d=b.flow.evalDraft();assert.equal(d.rating,4);assert.equal(d.wentWell,'Clear explanations and answered questions well.');assert.equal(d.improve,'Slow down at the end.');assert.equal(d.date,'2026-09-11');assert.equal(writes,0);});
await test('explicit submit sends exactly the reviewed fields',async()=>{let saved;const b=await evalApp(async d=>{saved=d;return {};});await reviewEval(b);const r=await b.flow.handleEvalMessage('submit it');assert.match(r.text,/Submitted: Blake Example/);assert.equal(saved.rating,4);assert.equal(saved.improve,'Slow down at the end.');assert.equal(saved.owner,'demo');assert.equal(b.flow.evalDraft(),null);});
await test('good is kept as a comment, not assigned a numeric rating',async()=>{const b=await evalApp();await b.flow.handleEvalMessage('I have an eval to do');const r=await b.flow.handleEvalMessage('It was good');assert.match(r.text,/kept that comment/);assert.equal(b.flow.evalDraft().rating,null);assert.equal(b.flow.evalDraft().notes,'It was good');});
await test('one message can fill labeled feedback and retain its date',async()=>{const b=await evalApp();const r=await b.flow.handleEvalMessage('Draft an eval for Blake Example\nrating: 5; strengths: Clear voice.; improvements: none; notes: Warm welcome.; date: 2026-09-10');assert.equal(b.flow.evalDraft().phase,'review');assert.equal(b.flow.evalDraft().date,'2026-09-10');assert.equal(b.flow.evalDraft().wentWell,'Clear voice.');assert.match(r.text,/Nothing has been submitted/);});
await test('several claims require explicit guide selection',async()=>{const b=await evalApp();b.state.guides.push({...b.state.guides[0],id:'eval-two',name:'Avery Sample'});const r=await b.flow.handleEvalMessage('I need to do an eval');assert.match(r.text,/Which of your claimed/);assert.equal(b.flow.evalDraft().evalId,'');await b.flow.handleEvalMessage('2');assert.equal(b.flow.evalDraft().evalId,'eval-two');});
await test('an unknown named person never defaults to the sole claim',async()=>{const b=await evalApp();await b.flow.handleEvalMessage('Draft an eval for Someone Else');assert.equal(b.flow.evalDraft().evalId,'');});
await test('training access and ownership filter the available claims',async()=>{const b=await evalApp();b.state.role.in_training=false;assert.match((await b.flow.handleEvalMessage('I need to do an eval')).text,/training members/);b.state.role.in_training=true;b.state.guides[0].evaluatorId='another-user';assert.match((await b.flow.handleEvalMessage('I need to do an eval')).text,/no claimed evaluations/);});
await test('unfinished draft cannot submit',async()=>{let n=0;const b=await evalApp(async()=>{n++;return {};});await b.flow.handleEvalMessage('I need to do an eval');const d=b.flow.evalDraft();assert.match((await b.flow.submitEvalDraft(d.draftId,d.revision)).text,/Finish the draft/);assert.equal(n,0);});
await test('edits invalidate stale submit buttons',async()=>{let n=0;const b=await evalApp(async()=>{n++;return {};});await reviewEval(b);const old=b.flow.evalDraft();b.flow.editEvalDraft(old.draftId,old.revision,{rating:5});assert.match((await b.flow.submitEvalDraft(old.draftId,old.revision)).text,/draft changed/);assert.equal(n,0);assert.equal(b.flow.evalDraft().rating,5);});
await test('submission failure preserves feedback for retry',async()=>{const b=await evalApp(async()=>{throw Error('offline');});await reviewEval(b);const r=await b.flow.handleEvalMessage('submit it');assert.match(r.text,/could not confirm/);assert.equal(b.flow.evalDraft().phase,'review');assert.equal(b.flow.evalDraft().wentWell,'Clear explanations and answered questions well.');});
await test('simultaneous submission requests create one write',async()=>{let done,n=0;const b=await evalApp(()=>{n++;return new Promise(r=>done=r);});await reviewEval(b);const d=b.flow.evalDraft();const first=b.flow.submitEvalDraft(d.draftId,d.revision);const second=await b.flow.submitEvalDraft(d.draftId,d.revision);assert.match(second.text,/already being submitted/);assert.equal(n,1);done({});await first;});
await test('cancellation cannot claim to undo a submission already in flight',async()=>{let done;const b=await evalApp(()=>new Promise(r=>done=r));await reviewEval(b);const pending=b.flow.handleEvalMessage('submit it');const r=await b.flow.handleEvalMessage('cancel draft');assert.match(r.text,/cannot be cancelled/);done({});await pending;});
await test('draft can be discarded before submission',async()=>{let n=0;const b=await evalApp(async()=>{n++;return {};});await reviewEval(b);assert.match((await b.flow.handleEvalMessage('cancel draft')).text,/Nothing was submitted/);assert.equal(b.flow.evalDraft(),null);assert.equal(n,0);});
await test('UI sign-out teardown removes the eval draft as well',async()=>{const b=await evalApp();await reviewEval(b);const ui=await b.get('js/core/vanessa-ui.js');ui.resetVanessa();assert.equal(b.flow.evalDraft(),null);});
await test('a read-only question during drafting does not become feedback',async()=>{const b=await evalApp();await b.flow.handleEvalMessage('I need to do an eval');await b.flow.handleEvalMessage('4');assert.equal(await b.flow.handleEvalMessage('Who is leading tours today?'),null);assert.equal(b.flow.evalDraft().wentWell,'');});
await test('how-to question does not start a submission flow',async()=>{const b=await evalApp();assert.equal(await b.flow.handleEvalMessage('How do I submit an eval?'),null);});
await test('blank feedback and invalid ratings/dates are rejected before writing',async()=>{const b=await evalApp();const {validateEvalDraft}=await b.get('js/core/vanessa-eval-submit.js');const d={evalId:'e',rating:4,wentWell:'Clear',improve:'',notes:'',date:'2026-09-11',time:'10:00'};assert.throws(()=>validateEvalDraft({...d,wentWell:''}),/Add feedback/);assert.throws(()=>validateEvalDraft({...d,rating:6}),/1 to 5/);assert.throws(()=>validateEvalDraft({...d,date:'2026-02-30'}),/valid tour date/);});
await test('submission uses one atomic endpoint with exact feedback',async()=>{let requests=[];const b=await app({window:{CONFIG:{SUPABASE_URL:'https://example.invalid',SUPABASE_KEY:'fictional'},addEventListener(){}},fetch:async(url,options)=>{requests.push({url,options});return {status:200,ok:true,text:async()=>' {"eval_id":"eval-demo","already":false} '};}});const service=await b.get('js/core/vanessa-eval-submit.js');await service.submitReviewedEval({owner:'demo',evalId:'eval-demo',rating:4,wentWell:'My exact feedback.',improve:'',notes:'',date:'2026-09-11',time:'10:00'});assert.equal(requests.length,1);assert.match(requests[0].url,/rpc\/submit_own_eval$/);const body=JSON.parse(requests[0].options.body);assert.equal(body.p_went_well,'My exact feedback.');assert.equal(body.p_tour_date,'2026-09-11');});
await test('server ownership rejection does not report success',async()=>{const b=await app({window:{CONFIG:{SUPABASE_URL:'https://example.invalid',SUPABASE_KEY:'fictional'},addEventListener(){}},fetch:async()=>({status:400,ok:false,text:async()=>' {"message":"This evaluation is no longer claimed by you."} '})});const service=await b.get('js/core/vanessa-eval-submit.js');await assert.rejects(service.submitReviewedEval({owner:'demo',evalId:'e',rating:4,wentWell:'Clear voice',improve:'',notes:'',date:'',time:''}),/no longer claimed/);});
await test('missing RPC gives the one-time SQL setup instruction',async()=>{const b=await app({window:{CONFIG:{SUPABASE_URL:'https://example.invalid',SUPABASE_KEY:'fictional'},addEventListener(){}},fetch:async()=>({status:404,ok:false,text:async()=>' {"message":"Could not find the function public.submit_own_eval in the schema cache"} '})});const service=await b.get('js/core/vanessa-eval-submit.js');await assert.rejects(service.submitReviewedEval({owner:'demo',evalId:'e',rating:4,wentWell:'Clear voice',improve:'',notes:'',date:'',time:''}),/09-vanessa-submit.sql/);});
await test('premature chat submit is not stored as feedback',async()=>{const b=await evalApp();await b.flow.handleEvalMessage('I need to do an eval');await b.flow.handleEvalMessage('4');const r=await b.flow.handleEvalMessage('submit it');assert.match(r.text,/Finish the missing fields/);assert.equal(b.flow.evalDraft().wentWell,'');assert.equal(b.flow.evalDraft().phase,'wentWell');});

await test('saved draft survives a fresh application context',async()=>{const b=await evalApp();await reviewEval(b);const fresh=await app({localStorage:b.context.localStorage});fresh.state.guides=b.state.guides;const flow=await fresh.get('js/core/vanessa-eval.js');flow.registerEvalActions({load:async()=>{},submit:async()=>({})});assert.equal(flow.evalDraft(),null);assert.equal(flow.savedEvalSummary().name,'Blake Example');await flow.handleEvalMessage('continue my eval');assert.equal(flow.evalDraft().wentWell,'Clear explanations and answered questions well.');assert.equal(flow.evalDraft().phase,'review');});
await test('partial draft resumes at the next unanswered field',async()=>{const b=await evalApp();await b.flow.handleEvalMessage('I have an eval to do');await b.flow.handleEvalMessage('four');b.flow.resetEvalFlow();const reply=await b.flow.handleEvalMessage('continue my eval');assert.match(reply.text,/What went well/);assert.equal(b.flow.evalDraft().rating,4);});
await test('another signed-in account cannot load the saved draft',async()=>{const b=await evalApp();await reviewEval(b);b.flow.resetEvalFlow();b.state.me={id:'someone-else',full_name:'Other User'};assert.equal(b.flow.savedEvalSummary(),null);assert.match((await b.flow.handleEvalMessage('continue my eval')).text,/no saved draft/);b.state.me={id:'demo',full_name:'Demo User'};assert.equal(b.flow.savedEvalSummary().name,'Blake Example');});
await test('new draft request does not overwrite existing saved feedback',async()=>{const b=await evalApp();await reviewEval(b);b.flow.resetEvalFlow();assert.match((await b.flow.handleEvalMessage('Help me write an eval')).text,/saved draft for Blake/);await b.flow.handleEvalMessage('continue my eval');assert.equal(b.flow.evalDraft().rating,4);});
await test('resume rechecks ownership and retains inaccessible draft',async()=>{const b=await evalApp();await reviewEval(b);b.flow.resetEvalFlow();b.state.guides[0].evaluatorId='other';assert.match((await b.flow.handleEvalMessage('continue my eval')).text,/no longer claimed/);assert.equal(b.flow.evalDraft(),null);assert.ok(b.flow.savedEvalSummary());});
await test('explicit discard removes persisted draft',async()=>{const b=await evalApp();await reviewEval(b);b.flow.resetEvalFlow();await b.flow.handleEvalMessage('discard saved draft');assert.equal(b.flow.savedEvalSummary(),null);});
await test('successful submission removes persisted draft',async()=>{const b=await evalApp();await reviewEval(b);await b.flow.handleEvalMessage('submit it');assert.equal(b.flow.savedEvalSummary(),null);});
await test('sign-out clears active flow but retains account draft',async()=>{const b=await evalApp();await reviewEval(b);const ui=await b.get('js/core/vanessa-ui.js');ui.resetVanessa();assert.equal(b.flow.evalDraft(),null);assert.ok(b.flow.savedEvalSummary());});
await test('storage failure is reported without breaking drafting',async()=>{const b=await app({localStorage:{getItem(){return null;},setItem(){throw Error('full');},removeItem(){}}});b.state.guides=[{id:'e',name:'Blake Example',status:'claimed',evaluatorId:'demo',date:'',time:''}];const flow=await b.get('js/core/vanessa-eval.js');flow.registerEvalActions({load:async()=>{}});await flow.handleEvalMessage('I need to do an eval');await flow.handleEvalMessage('4');assert.equal(flow.evalDraft().saved,false);assert.equal(flow.evalDraft().rating,4);});
await test('typing into a field saves before Update draft is pressed',async()=>{const b=await evalApp();await b.flow.handleEvalMessage('I need to do an eval');let d=b.flow.evalDraft();b.flow.bufferEvalDraft(d.draftId,d.revision,{wentWell:'Notes typed directly.'});b.flow.resetEvalFlow();await b.flow.handleEvalMessage('continue my eval');assert.equal(b.flow.evalDraft().wentWell,'Notes typed directly.');});
await test('corrupt saved JSON is ignored without throwing',async()=>{const b=await app({localStorage:{getItem(){return '{bad';},setItem(){},removeItem(){}}});const store=await b.get('js/core/vanessa-draft-store.js');assert.equal(store.loadSavedDraft(),null);});
async function tourApp(){const b=await app();b.state.guideToursLoaded=true;b.state.guides=[{id:'a',name:'First Guide',rank:1,priority:'First Priority',status:'open',tours:[{date:'2026-09-15',start:'14:00'}]},{id:'b',name:'Second Guide',rank:2,priority:'Second Priority',status:'open',tours:[{date:'2026-09-15',start:'10:00'}]},{id:'c',name:'Claimed Guide',rank:1,priority:'First Priority',status:'claimed',evaluatorId:'demo',tours:[{date:'2026-09-15',start:'15:00'}]},{id:'d',name:'Other Day',rank:1,priority:'First Priority',status:'open',tours:[{date:'2026-09-16',start:'14:00'}]}];return b;}
await test('eval tour matching filters the date and lists priorities in order',async()=>{const b=await tourApp();const r=b.v.ask('Who needs an eval and has a tour on 2026-09-15?');assert.match(r.text,/First Guide/);assert.match(r.text,/Second Guide/);assert.doesNotMatch(r.text,/Claimed Guide|Other Day/);assert.ok(r.text.indexOf('First Guide')<r.text.indexOf('Second Guide'));});
await test('eval tour matching combines priority and time filters',async()=>{const b=await tourApp();const r=b.v.ask('Find first priority eval tours on 2026-09-15 after 1 pm');assert.match(r.text,/First Guide/);assert.doesNotMatch(r.text,/Second Guide/);});
await test('my eval tour search includes only my claims',async()=>{const b=await tourApp();const r=b.v.ask('Which of my evals have tours on 2026-09-15?');assert.match(r.text,/Claimed Guide/);assert.doesNotMatch(r.text,/First Guide|Second Guide/);});
await test('missing schedule is not reported as no matching tours',async()=>{const b=await tourApp();b.state.guideToursLoaded=false;assert.match(b.v.ask('Who needs an eval and has a tour on 2026-09-15?').text,/has not loaded/);});
await test('tour search asks for a date instead of guessing',async()=>{const b=await tourApp();assert.match(b.v.ask('Find a tour to evaluate').text,/Which day/);});
function speechMock(){let instance;class Recognition{constructor(){instance=this;this.started=0;this.aborted=0;}start(){this.started++;}stop(){this.onend?.();}abort(){this.aborted++;}}return {Recognition,get:()=>instance};}
await test('voice start is explicit and results remain a reviewable transcript',async()=>{const mock=speechMock();const b=await app({SpeechRecognition:mock.Recognition});const voice=await b.get('js/core/vanessa-voice.js');assert.equal(mock.get(),undefined);voice.startVoice();assert.equal(mock.get().started,1);mock.get().onresult({results:[[{transcript:'He explained it clearly.'}]]});assert.equal(voice.voiceState().text,'He explained it clearly.');voice.stopVoice();assert.equal(voice.voiceState().phase,'review');voice.resetVoice();});
await test('dictated submission command is only transcript text',async()=>{const mock=speechMock();const b=await app({SpeechRecognition:mock.Recognition});const voice=await b.get('js/core/vanessa-voice.js');voice.startVoice();mock.get().onresult({results:[[{transcript:'submit it'}]]});voice.stopVoice();assert.equal(voice.voiceState().text,'submit it');assert.equal(voice.voiceState().phase,'review');voice.resetVoice();});
await test('late speech results are ignored after reset',async()=>{const mock=speechMock();const b=await app({SpeechRecognition:mock.Recognition});const voice=await b.get('js/core/vanessa-voice.js');voice.startVoice();const old=mock.get();voice.resetVoice();old.onresult({results:[[{transcript:'previous account notes'}]]});assert.equal(voice.voiceState().text,'');assert.equal(old.aborted,1);});
await test('microphone denial produces an actionable error',async()=>{const mock=speechMock();const b=await app({SpeechRecognition:mock.Recognition});const voice=await b.get('js/core/vanessa-voice.js');voice.startVoice();mock.get().onerror({error:'not-allowed'});assert.match(voice.voiceState().message,/permission was denied/);assert.equal(voice.voiceState().phase,'error');voice.resetVoice();});
await test('unsupported speech recognition leaves typing available',async()=>{const b=await app();const voice=await b.get('js/core/vanessa-voice.js');voice.startVoice();assert.equal(voice.voiceState().phase,'error');assert.match(voice.voiceState().message,/still type/);});
await test('two record clicks do not create two microphone sessions',async()=>{const mock=speechMock();const b=await app({SpeechRecognition:mock.Recognition});const voice=await b.get('js/core/vanessa-voice.js');voice.startVoice();const first=mock.get();voice.startVoice();assert.equal(mock.get(),first);assert.equal(first.started,1);voice.resetVoice();});
await test('tour searches during drafting are not stored as comments',async()=>{const b=await evalApp();await b.flow.handleEvalMessage('I need to do an eval');await b.flow.handleEvalMessage('4');assert.equal(await b.flow.handleEvalMessage('Find first priority eval tours Tuesday'),null);assert.equal(b.flow.evalDraft().wentWell,'');});
await test('last priority filter does not include higher priority guides',async()=>{const b=await tourApp();b.state.guides.push({id:'last',name:'Last Guide',rank:6,priority:'Last Priority',status:'open',tours:[{date:'2026-09-15',start:'10:00'}]});const r=b.v.ask('Find last priority eval tours on 2026-09-15');assert.match(r.text,/Last Guide/);assert.doesNotMatch(r.text,/First Guide|Second Guide/);});
await test('task summary lists only own pending evals and saved draft',async()=>{const b=await evalApp();await b.flow.handleEvalMessage('I need to do an eval');b.state.guides.push({name:'Other Person',status:'claimed',evaluatorId:'other',date:'2026-09-11'});const r=b.v.ask('What do I need to do?');assert.match(r.text,/1 claimed evaluation/);assert.match(r.text,/Saved draft: Blake/);assert.doesNotMatch(r.text,/Other Person/);});
await test('task summary reports missing loaded data',async()=>{const b=await app();b.state.loadedAt=null;assert.match(b.v.ask('my tasks').text,/not loaded/);});
await test('task question does not become draft feedback',async()=>{const b=await evalApp();await b.flow.handleEvalMessage('I need to do an eval');assert.equal(await b.flow.handleEvalMessage('What do I need to do?'),null);});
await test('vague feedback asks for detail without invention',async()=>{const b=await evalApp();await b.flow.handleEvalMessage('I need to do an eval');await b.flow.handleEvalMessage('4');const r=await b.flow.handleEvalMessage('good but quiet');assert.match(r.text,/hard to hear/);assert.equal(b.flow.evalDraft().wentWell,'good but quiet');await b.flow.handleEvalMessage('Hard to hear at the back.');assert.equal(b.flow.evalDraft().wentWell,'good but quiet\nHard to hear at the back.');assert.equal(b.flow.evalDraft().phase,'improve');});
await test('clarification is optional and retains original wording',async()=>{const b=await evalApp();await b.flow.handleEvalMessage('I need to do an eval');await b.flow.handleEvalMessage('4');await b.flow.handleEvalMessage('good');await b.flow.handleEvalMessage('keep it');assert.equal(b.flow.evalDraft().wentWell,'good');assert.equal(b.flow.evalDraft().phase,'improve');});
await test('receipt displays server timestamp and saved feedback',async()=>{const receipt={id:'receipt-123',eval_id:'eval-demo',submitted_by:'demo',created_at:'2026-09-11T16:00:00Z',rating:4,went_well:'Exact saved feedback',improve:'',notes:'',tour_date:'2026-09-11',tour_time:'10:00:00'};const b=await app({window:{CONFIG:{SUPABASE_URL:'https://example.invalid',SUPABASE_KEY:'fake'},addEventListener(){}},fetch:async()=>({ok:true,status:200,text:async()=>JSON.stringify({eval_id:'eval-demo',receipt})})});const service=await b.get('js/core/vanessa-eval-submit.js');const result=await service.submitReviewedEval({owner:'demo',evalId:'eval-demo',rating:4,wentWell:'Exact saved feedback',improve:'',notes:'',date:'2026-09-11',time:'10:00'});assert.match(result.receipt,/receipt-123/);assert.match(result.receipt,/2026-09-11T16:00:00Z/);assert.match(result.receipt,/Exact saved feedback/);});
await test('submission reply includes receipt in conversation',async()=>{const b=await evalApp(async()=>({receipt:'Receipt: example-id'}));await reviewEval(b);assert.match((await b.flow.handleEvalMessage('submit it')).text,/Receipt: example-id/);});
async function presenceApp(call){const b=await app({setInterval,clearInterval});const {createPresence}=await b.get('js/core/presence.js');let clock=0,visible=true,drawn=[];const tracker=createPresence({call,draw:x=>drawn.push(x),visible:()=>visible,now:()=>clock,schedule:()=>1,unschedule:()=>{},tabId:'test-tab'});return {tracker,drawn,advance:n=>clock+=n,hide:()=>visible=false};}
await test('presence publishes active then idle heartbeat',async()=>{const calls=[];const b=await presenceApp(async(n,args)=>{calls.push({n,args});return [];});await b.tracker.tick();assert.equal(calls[0].args.p_active,true);b.advance(300001);await b.tracker.tick();assert.equal(calls[2].args.p_active,false);b.tracker.stop();});
await test('hidden tab withdraws its heartbeat',async()=>{const calls=[];const b=await presenceApp(async(n,args)=>{calls.push({n,args});return [];});b.hide();await b.tracker.tick();assert.equal(calls[0].args.p_active,false);b.tracker.stop();});
await test('presence errors clear stale names',async()=>{const b=await presenceApp(async()=>{throw Error('offline');});await b.tracker.tick();assert.equal(b.drawn.at(-1).error,true);assert.equal(b.drawn.at(-1).users.length,0);});
await test('presence ignores responses after signout stop',async()=>{let done;const b=await presenceApp(()=>new Promise(r=>done=r));const pending=b.tracker.tick();b.tracker.stop();done([]);await pending;assert.equal(b.drawn.length,1);assert.equal(b.drawn[0].users.length,0);});
console.log(`\n${checks} regression checks passed.`);
